version: 0.2

phases:
  install:
    commands:
      - curl -Ls https://github.com/gohugoio/hugo/releases/download/v0.101.0/hugo_0.101.0_Linux-64bit.tar.gz -o /tmp/hugo.tar.gz
      - tar xf /tmp/hugo.tar.gz -C /tmp
      - mv /tmp/hugo /usr/bin/hugo
      - rm -rf /tmp/hugo*
  build:
    commands:
      - curl -L https://github.com/eiKatou/eikatou.net_theme/archive/main.zip -o themes/eikatou.net_theme-main.zip
      - unzip themes/eikatou.net_theme-main.zip -d themes/
      - mv themes/eikatou.net_theme-main themes/eikatou.net_theme
      - hugo --theme=eikatou.net_theme
      - mv public blog
  post_build:
    commands:
      - aws s3 rm s3://eikatou.net/blog/index.html
      - aws s3 rm s3://eikatou.net/blog/index.xml
      - aws s3 rm s3://eikatou.net/blog/archives/index.html
      - aws s3 rm s3://eikatou.net/blog/archives/index.xml
      - aws s3 rm s3://eikatou.net/blog/tags/index.html
      - aws s3 rm s3://eikatou.net/blog/tags/index.xml
      - aws s3 sync --size-only --delete blog s3://eikatou.net/blog/ --exclude *.tmp --exclude .DS_Store
      - aws s3 cp s3://eikatou.net/google8f78f6eb936c1d12.html s3://eikatou.net/blog/google8f78f6eb936c1d12.html
      - aws s3 ls s3://eikatou.net
      - aws cloudfront create-invalidation --distribution-id E1SK2Q7CXNWG24 --paths /blog/*