baseURL = "https://eikatou.net/blog"
canonifyurls = true
languageCode = "ja"
defaultContentLanguage = "ja"
title = "ei's diary"
paginate = 3
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
googleAnalytics = "UA-29096623-1"

[markup.goldmark.renderer]
  unsafe = true

[Author]
  name = "ei"
  github = "eiKatou"

[Params]
#  subtitle = "Once you stop learning, you start dying."
#  logo="/uploads/2011/10/16.png"
#  logo="./icon/greeneyecat.jpg"
#  favicon = "img/favicon.ico"
#  dateFormat = "January 2, 2006"
  dateFormat = "2006年01月02日"
#  commit = false
  rss = true
#  comments = true

[taxonomies]
  archive = "archives"
  tag = "tags"

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3
    identifier = "about"
[[menu.main]]
    name = "Archives"
    weight = 3
    url = "archives/"
[[menu.main]]
    name = "Tags"
    weight = 3
    url = "tags/"