baseURL = "https://eikatou.net/blog/"
canonifyurls = true
languageCode = "ja"
defaultContentLanguage = "ja"
title = "ei's diary"
paginate = 5
metaDataFormat = "yaml"
googleAnalytics = "UA-29096623-1"
pygmentsCodeFences = true
pygmentsUseClasses = true

[markup.goldmark.renderer]
  unsafe = true

[Author]
  name = "ei"
  github = "eiKatou"

[Params]
#  subtitle = "Once you stop learning, you start dying."
  dateFormat = "2006年01月02日"
  since = "2010"
  rss = true

[taxonomies]
  archive = "archives"
  tag = "tags"
